name: Fun with autodev

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup autodev
        run: |
          git clone https://github.com/Sakshi-Jha-Geminian/autodev.git
          cd autodev
          ls -lrt autodev
          chmod +x install.sh
          ./install.sh
          autodev "setup web dev"
          
          

          
